name: NX_CI

on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  build_NX:
      runs-on: ubuntu-latest
    
      steps:
        - name: Extract owner and repo
          uses: jungwinter/split@v2
          id: repo
          with:
            seperator: /
            msg: ${{ github.repository }}
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: master
            submodules: recursive
        - name: Use Docker Build
          uses: actions-hub/docker/cli@master
          env:
              SKIP_LOGIN: true
        - run: |
               docker run -t --rm --name builder -v `pwd`:`pwd` -w `pwd` zerofo/ns_dev:0.9b2 make
               mkdir -p switch/.overlays/
               cp ./out/*.ovl switch/.overlays/
               zip -r EdiZon-Overlay.zip switch
                
        - name: Upload file
          uses: actions/upload-artifact@v3
          with:
            name: ${{ steps.repo.outputs._1 }} 
            path: EdiZon-Overlay.zip
        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v3
          with:
            repo_token: ${{ secrets.release_token }}
            file: EdiZon-Overlay.zip
            tag: ${{ github.ref }}
            overwrite: true
            file_glob: true
