name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - name: Extract owner and repo
      uses: winterjung/split@v2.1.0
      id: repo
      with:
        msg: ${{ github.repository }}
        separator: '/'
    - name: Checkout project
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Build project
      run: |
          apt update
          apt install -y libjson-c-dev
          dkp-pacman -Syu --noconfirm
          dkp-pacman -Syu --noconfirm switch-dev deko3d devkita64-cmake switch-cmake switch-pkg-config devkitA64 devkitA64-gdb switch-tools general-tools uam devkitARM devkitARM-gdb devkitarm-rules switch-portlibs devkitARM switch-curl switch-zziplib switch-mbedtls switch-jansson
          git config --global --add safe.directory `pwd`
          git submodule update --remote && make -j2
          ls

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: out
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.release_token }}
        file: ./out/*ovl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        make_latest: true 
